### ISSUE TITLE
185-199-110-153.mcdn.bilivideo.cn

### ISSUE THREAD

**Issue by cherinyy** [journey-ad/bilicdn#2]
```
dig +dnssec +short +tcp 185-199-110-153.mcdn.bilivideo.cn "@dns.google"
185.199.110.153
```

**Comment by Mabbs** [comment]
> dig +dnssec +short +tcp 185-199-110-153.mcdn.bilivideo.cn "@dns.google"
> 185.199.110.153

```
dig +short 185_199_110_153.mcdn.bilivideo.cn "@dns.google"
185.199.110.153
```

**Comment by cherinyy** [comment]
> > dig +dnssec +short +tcp 185-199-110-153.mcdn.bilivideo.cn "@dns.google"
> > 185.199.110.153
> 
> ```
> dig +short 185_199_110_153.mcdn.bilivideo.cn "@dns.google"
> 185.199.110.153
> ```

好像并不存在？
```
dig +tcp 185_199_110_153.mcdn.bilivideo.cn "@119.29.29.29"

; <<>> DiG 9.17.15 <<>> +tcp 185_199_110_153.mcdn.bilivideo.cn @119.29.29.29
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10738
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 321757b2f1329ecf4e79db9760d7573f40ce2700f9347c34 (good)
;; QUESTION SECTION:
;185_199_110_153.mcdn.bilivideo.cn. IN  A

;; Query time: 53 msec
;; SERVER: 119.29.29.29#53(119.29.29.29) (TCP)
;; WHEN: Sun Jun 27 00:35:13 China Standard Time 2021
;; MSG SIZE  rcvd: 90
```

**Comment by Mabbs** [comment]
> > > dig +dnssec +short +tcp 185-199-110-153.mcdn.bilivideo.cn "@dns.google"
> > > 185.199.110.153
> > 
> > 
> > ```
> > dig +short 185_199_110_153.mcdn.bilivideo.cn "@dns.google"
> > 185.199.110.153
> > ```
> 
> 好像并不存在？
> 
> ```
> dig +tcp 185_199_110_153.mcdn.bilivideo.cn "@119.29.29.29"
> 
> ; <<>> DiG 9.17.15 <<>> +tcp 185_199_110_153.mcdn.bilivideo.cn @119.29.29.29
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10738
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 4096
> ; COOKIE: 321757b2f1329ecf4e79db9760d7573f40ce2700f9347c34 (good)
> ;; QUESTION SECTION:
> ;185_199_110_153.mcdn.bilivideo.cn. IN  A
> 
> ;; Query time: 53 msec
> ;; SERVER: 119.29.29.29#53(119.29.29.29) (TCP)
> ;; WHEN: Sun Jun 27 00:35:13 China Standard Time 2021
> ;; MSG SIZE  rcvd: 90
> ```

emmmm因为带下划线不是标准的域名格式，但是用好像是可以用的，直接访问没有问题

**Comment by cherinyy** [comment]
NXDOMAIN
